
import { NgModule } from '@angular/core';
import { LucideAngularModule, Inbox, FilePlus, LayoutDashboard, Building2, Bot, Shield, ClipboardCheck, BarChart3, FileText, Settings, ChevronDown, ChevronRight, Gauge, FileCheck, Users, AlertTriangle, ArrowUpRight, Database, Lightbulb, Bell, ScrollText, BookOpen, Briefcase, ListTodo, TrendingUp, Layers, FolderOpen, Library, Scale, FileSearch, UserCog, Workflow, Link2, HelpCircle, Info, CheckCircle, Eye, Target, Activity, Search, Globe, Sidebar, Share2, CheckCircle2, Check, Loader2, Circle, TrendingDown, Clock, Home, Key, FlaskConical, Sparkles, Code2, Terminal, LifeBuoy, Radar, Hammer, Presentation, ArrowRight, PanelLeft, Headphones, ShieldAlert, Cpu, PenTool, PieChart, GraduationCap, FileStack, ClipboardList, Wrench, User, ChevronUp, UploadCloud, File, ScanSearch, ShieldCheck, History, BrainCircuit, RotateCcw, Send, MoreHorizontal, Pause, Plus, FileEdit, AlertCircle, Play, ArrowLeft, Maximize2, FileLineChart, FileBarChart2, MessageSquare, GitBranch, Crosshair, ListChecks, Save, Zap, Layout, Filter, LayoutTemplate, X, Download, GitMerge, LayoutGrid, Telescope, Gem, PlusCircle, List, ExternalLink, Edit3, Edit2, Paperclip, BarChart2, RefreshCw, Server, Tag, Quote, CheckSquare, FileBox, XCircle, Rocket } from 'lucide-angular';

@NgModule({
    imports: [
        LucideAngularModule.pick({
            Inbox, FilePlus, LayoutDashboard, Building2, Bot, Shield, ClipboardCheck, BarChart3, FileText, Settings, ChevronDown, ChevronRight, Gauge, FileCheck, Users, AlertTriangle, ArrowUpRight, Database, Lightbulb, Bell, ScrollText, BookOpen, Briefcase, ListTodo, TrendingUp, Layers, FolderOpen, Library, Scale, FileSearch, UserCog, Workflow, Link2, HelpCircle, Info, CheckCircle, Eye, Target, Activity, Search, Globe, Sidebar, Share2, CheckCircle2, Check, Loader2, Circle, TrendingDown, Clock, Home, Key, FlaskConical, Sparkles, Code2, Terminal, LifeBuoy, Radar, Hammer, Presentation, ArrowRight, PanelLeft, Headphones, ShieldAlert, Cpu, PenTool, PieChart, GraduationCap, FileStack, ClipboardList, Wrench, User, ChevronUp, UploadCloud, File, ScanSearch, ShieldCheck, History, BrainCircuit, RotateCcw, Send, MoreHorizontal, Pause, Plus, FileEdit, AlertCircle, Play, ArrowLeft, Maximize2, FileLineChart, FileBarChart2, MessageSquare, GitBranch, Crosshair, ListChecks, Save, Zap, Layout, Filter, LayoutTemplate, X, Download, GitMerge, LayoutGrid, Telescope, Gem, PlusCircle, List, ExternalLink, Edit3, Edit2, Paperclip, BarChart2, RefreshCw, Server, Tag, Quote, CheckSquare, FileBox, XCircle, Rocket
        })
    ],
    exports: [LucideAngularModule]
})
export class SharedIconsModule { }
